config/routes.rb
Rails.application.routes.draw do
  resources :texts
  # resources :messages
  resources :posts
  resources :profiles
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'comments#index' # ここを追記します
  get 'comments/index' # 自動で設定されたルーティング
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :thumbnail, PictureUploader
    belongs_to :user
    has_many :texts
end

app/models/profile.rb
class Profile < ApplicationRecord
    mount_uploader :thumbnail, PictureUploader
    belongs_to :user
end

app/models/text.rb
class Text < ApplicationRecord
    validates :content, presence: true
    # createの後にコミットする { TextBroadcastJobのperformを遅延実行 引数はself }
    after_create_commit { TextBroadcastJob.perform_later self }
    #TextBroadcastJobBroadcastJob.perform_later self でself以外に@profileを持たせてもいい
    #selfはコメント欄に書かれたメッセージの内容
    # belongs_to :post
    # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :email, :password, presence: true
         
  has_one :profile
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
  
  # GET /posts/1
  # GET /posts/1.json
  def show
    @profile = Profile.find_by(:user_id => current_user.id)
    user = Post.find_by(:id => params[:id])
    @user_name = Profile.find_by(:user_id => user.user_id)
    # print("==========================")
    # print(@user_name.name)
    
    if !Text.where("post_id" =>  params[:id]).nil?
      @texts = Text.where("post_id" => params[:id])
    end
    # @profiles = Profiles.where("user_id" => params[:id])
      # @texts = Text.where(:post_id => params[:id]).where(text)
    # end
  end

  # GET /posts/new
  def new
    # @post = Post.new
    @post = Post.new(:user_id => current_user.id)#Post.find_or_create_by(:user_id => current_user.id)
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id != current_user.id 
      flash[:notice] = "他のユーザーの投稿は編集できません。"
      redirect_to posts_path
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿が保存されました。' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '投稿が更新されました。' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user_id != current_user.id
         flash[:notice] = "他のユーザーの投稿は削除できません。"
         redirect_to posts_path#action: :index
    else
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: '投稿が削除されました。' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :name, :thumbnail, :price, :introduction)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.find_or_create_by(:user_id => current_user.id)
    redirect_to edit_profile_url(@profile)
  end

  # GET /profiles/1/edit
  def edit
    if @profile.user_id != current_user.id 
      flash[:notice] = "他のユーザーのプロフィールは編集できません。"
      redirect_to profiles_path
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'プロフィールが更新されました。' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'プロフィールが更新されました。' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    if @profile.user_id != current_user.id
      flash[:notice] = "他のユーザーのプロフィールは削除できません。"
      redirect_to profiles_path
    else
      @profile.destroy
      respond_to do |format|
        format.html { redirect_to profiles_url, notice: 'プロフィールが削除されました。' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:user_id, :name, :thumbnail, :birthday)
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new(:user_id => current_user.id) #textsをuser_idとpost_idに紐付ける条件をここに書く
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def text_params
      params.require(:text).permit(:content, :user_id, :post_id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/comments/index.html.erb
<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
    <span class="mt-4" style="float:right"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-danger text-white border-danger' %></span><br><br>
    <hr class="mt-0" style="height:4px; background-color:#49b99e; border:none;">
    <br><br><br><br>
    <div>
      <h1 style="text-align:center;"> メールアドレス： <span style="color:#49b99e"><%= current_user.email %></span> さんがログインしています。</h1><br>
      <div style="text-align:center;">
        <%= link_to 'プロフィール作成', new_profile_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
        <%= link_to 'プロフィール一覧', profiles_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
      </div>
    </div>
<% else %>
    <!-- ユーザーがログインしていなかった時の処理 -->
    <br><br><br><br><br><br><br><br>
    <h2 style="text-align:center;"> 現在ログインしていません。 </h2><br>
    <div style="text-align:center;">
      <%= link_to "ログイン", new_user_session_path, class: 'post btn btn-light border-primary text-primary font-weight-bold' %> <!-- ログイン画面に移行する -->
      <%= link_to "新規登録", new_user_registration_path, class: 'post btn btn-light border-primary text-primary font-weight-bold' %> <!-- 新規登録画面に移行する -->
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ItemShareApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link rel="stylesheet" href="assets/stylesheets/profiles.scss"> %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#f5f5f5;">
    <div class="container" style="padding-left:0; padding-right:0;">
      <p class="notice" style="text-align:center; color:blue; margin-top:40px;"><%= notice %></p>
      <p class="alert" style="text-align:center; color:red"><%= alert %></p>
      <% if user_signed_in? %>
        <%= link_to image_tag("logo.png", width:'170px', height:'70px'), profiles_path %>
      <% end %>
      <%= yield %>
    </div>  
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row field">
    <div class="col-4 col-form-label"> 
      <h5><%#= form.label :ユーザ %></h5>
    </div> 
    <div class="col-8">
      <%= form.hidden_field :user_id, value: post.user_id, class: 'form-control'  %>
    </div> 
  </div>
  
  <div class="form-group row field">
    <div class="col-3 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :名前 %>:</h5>
    </div>  
    <div class="col-9">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row field">
    <div class="col-3 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :写真 %>:</h5>
    </div>  
    <div class="col-9">
      <%= form.file_field :thumbnail %>
    </div>
  </div>

  <div class="form-group row field">
    <div class="col-3 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :価格 %>:</h5>
    </div>  
    <div class="col-9">
      <%= form.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row field">
    <div class="col-3 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :商品説明 %>:</h5>
    </div>  
    <div class="col-9">
      <%= form.text_area :introduction, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row actions">
    <div class="offset-5 col-7 mt-3">
      <%= form.submit('投稿', class: 'btn btn-primary border-primary text-white font-weight-bold')  %>
    </div>  
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="mt-4" style="float:right;">
    <%= link_to '戻る', posts_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
</div>
<hr style="height:4px; background-color:#49b99e; border:none;">
<div class="container">
  <div class="row">
    <div class="card col-sm-12 col-lg-8 mx-auto mt-5">
      <div class="card-body">
        <h1 style="text-align:center; font-weight:bold;">投稿編集</h1>
        <%= render 'form', post: @post %>
      </div>
    </div>    
  </div>
</div> 

app/views/posts/index.html.erb
<span class="mt-4" style="float:right"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-danger text-white border-danger' %></span>
<hr style="height:4px; background-color:#49b99e; border:none;">
<br>
<h1 class="font-weight-bold" style="text-align:center;">商品一覧</h1><br>
<div style="text-align:right; margin-bottom:30px;">
  <%= link_to '商品投稿', new_post_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
  <%= link_to '戻る', profiles_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
</div>

<div class="container">
  <div class="row rounded" style="background-color:lightgray;">
    <% @posts.each do |post| %>
      <div class="col-lg-4">
        <div class="card" style="margin:10px">
          <%= link_to post, class: "card" do %>
            <%= image_tag post.thumbnail.to_s, class: 'card-img-top', :size =>'250x250' %>   <%#, :size =>'250x250' %>
          <% end %>
          <div class="card-body" style="text-align:center;">
            <h4><%= post.name %></h4>
            <span class="rounded" style="background-color:gray; color:white; font-size:30px; padding-left:5px; padding-right:5px;"><%= post.price %></span>
            <p style="margin:15px;"><%= link_to '詳細', post, class: 'btn btn-light text-dark border-dark font-weight-bold' %><%= link_to '編集', edit_post_path(post), class: 'btn btn-light text-dark border-dark font-weight-bold' %><%= link_to '削除', post, method: :delete, data: { confirm: '削除します。よろしいですか？' }, class: 'btn btn-light text-dark border-dark font-weight-bold' %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>
<br>

app/views/posts/new.html.erb
<div class="pt-0 mt-4" style="float:right; margin-right:10px"><%= link_to '戻る', posts_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %></div>
<hr style="height:4px; background-color:#49b99e; border:none;">
<div class="container">
  <div class="row">
    <div class="card col-xs-7 col-lg-7 col-xl-6 mx-auto mt-3">
      <div class="card-body">
        <h1 class=" font-weight-bold" style="text-align:center;">商品投稿</h1>
        <%= render 'form', post: @post %>
      </div>
    </div>    
  </div>
</div> 

app/views/posts/show.html.erb
<%# <p>
  <strong>ユーザ:</strong>
  <%= @post.user_id %> 
<%# </p>  %> 
<div class="mt-4" style="float:right;">
  <%= link_to '編集', edit_post_path(@post), class: 'btn btn-light border-primary text-primary font-weight-bold' %> 
  <%= link_to '戻る', posts_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
</div>
<hr style="height:4px; background-color:#49b99e;">
<br>
<div class="container">
  <div class="row">
    <div class="card col-lg-6 border-0">
      <h2 class="pt-3 font-weight-bold" style="text-align:center;">商品詳細</h2>
      <br>
      <div class="mx-auto">
        <div class="card-body pt-4">
          <p style="padding-left:50px;">
            <strong style="font-size:18px;">投稿者:</strong>
            <span style="font-size:20px; padding-left:40px;"><%= @user_name.name %></span> 
          </p> 

          <% if @post.thumbnail? %>
            <p style="text-align:center;">
              <%= image_tag @post.thumbnail.to_s, :size =>'220x220' %>
            </p>
          <% end %>

          <p style="padding-left:50px;">
            <strong style="font-size:18px;">商品名:</strong>
            <span style="font-size:20px; padding-left:40px; padding-right:20px;"><%= @post.name %></span>
          </p>

          <p style="padding-left:50px;">
            <strong style="font-size:18px;">価格:</strong>
            <span style="font-size:20px; padding-left:55px;"><%= @post.price %></span>
          </p>

          <p style="padding-left:50px;">
            <p style="font-size:18px; padding-left:50px; font-weight:bold;">商品紹介:</p>
            <div style="padding-left:50px; padding-right:30px;">
              <span style="font-size:20px;"><%= @post.introduction %></span>
            </div>
          </p>
          <br>
        </div>
      </div>  
    </div>     
    <br>

    <div class="offset-lg-1 col-lg-5 border" style="background-color:white; padding-left:40px; padding-right:40px">
    <br>
      <h2 class="font-weight-bold" style="text-align:center;">コメント欄</h2><br>
      <div class="row">
        <%= label_tag :content, 'コメント:', class: "col-md-4 col-xl-3 pl-0" %><strong class="col-lg-8 col-xl-9" style="color:blue;">入力後にエンターを押してください。</strong>
        <%# text_field_tag(テキストボックス名, 初期文字列, {オプション1, オプション2,,,}) %>        <%#=  ↓ current_user.id、あるいは "data-user_id" => @profile.user_id  %>
        <%= text_area_tag :content, nil,  {:class => "col-md-12", "data-behavior" => "post_speaker", "data-user_id" => current_user.id, "data-post_id" => @post.id, "data-name" => @profile.name} %><br>  <%# コメントした内容に属性を持たせている。これでpost_channel.jsでエンターされたときにobjに値を入れられる。 %>
        <%# この上のとこclass以下何やっとるん？ %>                                        <%#=  ↑ posts_controller.rbに@profile = Profile.find_by(:user_id => current_user.id)を作ることで"data-user_id" => @profile.user_idを実現   %>
        <%# inputタグの属性と値を書いている。data-behavior属性にpost_speakerという値を持たせてjsの$(document).on ...で指定している。 %>
        <br>
      </div>  
      <div class="mt-4" id='texts'>
        <%= render @texts %>
        <%# render @textsとは、render partial: 'texts/text', collection: @textsの略 %>
        <%# メッセージ毎にtextsフォルダの_text.html.erbというパーシャルが適用される %>
      </div>
    </div>
  </div>
</div> 
<br>
<br>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# <div class="field"> %>
    <%# <%= form.label :user_id %> 
    <%# <%= form.number_field :user_id %> 
  <%# </div> %>
  <br>
  <div class="form-group row field">
    <div class="col-4 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :名前 %>:</h5>
    </div> 
    <div class="col-8">
      <%= form.text_field :name %>
    </div> 
  </div>

  <div class="form-group row field">
    <div class="col-4 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :画像 %>:</h5>
    </div>  
    <div class="col-8">
      <%= form.file_field :thumbnail %>
    </div>  
  </div>

  <div class="form-group row field">
    <div class="col-4 col-form-label">
      <h5 class=" font-weight-bold"><%= form.label :誕生日 %>:</h5>
    </div>
    <div class="col-8">
      <%= form.date_select(:birthday, start_year:Time.now.year, end_year:1900) %>
    </div>
  </div>

  <div class="form-group row actions">
    <div class="offset-5 col-7">
      <%= form.submit('更新', class: 'btn btn-primary') %>
    </div>  
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="mt-4" style="float:right;">
  <%= link_to '戻る', profiles_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
</div>
<hr style="height:4px; background-color:#49b99e; border:none;">
<div class="container">
  <div class="row">
    <div class="card col-xs-6 col-sm-11 col-md-8 col-lg-7 col-xl-6 mx-auto mt-5">
      <div class="card-body">
        <h1 style="text-align:center; font-weight-bold">プロフィール編集</h1>
        <%= render 'form', profile: @profile %>
      </div>
    </div>    
  </div>
</div> 

app/views/profiles/index.html.erb
<span class="border mt-4" style="float:right;"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-danger text-white border-danger'%></span>
<hr style="height:4px; background-color:#49b99e; border:none;">
<h1 class="font-weight-bold pt-3 pb-3" style="text-align:center;">プロフィール一覧</h1>
<br>
<div style="text-align:right; margin-bottom:30px;">
  <%= link_to '商品投稿', new_post_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %> 
  <%= link_to '商品一覧', posts_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
  <%= link_to 'プロフィール作成', new_profile_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
</div>
<div class="container">
  <div class="row">
    <table class="col-md-12" style="background-color:white; padding:30px;">
        <%# background-image:url('/assets/background.jpg'); %>
      <thead>
        <tr>
          <th class="pt-1" style="text-align:center; border-top:1px solid lightgrey; border-bottom:1px solid lightgrey;">名前</th>
          <th class="pt-1" style="text-align:center; border-top:1px solid lightgrey; border-bottom:1px solid lightgrey;">画像</th>
          <th class="pt-1" style="text-align:center; border-top:1px solid lightgrey; border-bottom:1px solid lightgrey;">誕生日</th>
          <th class="pt-1" colspan="3" style="border-top:1px solid lightgrey; border-bottom:1px solid lightgrey;"></th>
        </tr>
      </thead>

      <tbody>
        <% @profiles.each do |profile| %>
          <tr>
            <td style="border-top:1px solid lightgrey; text-align:center; padding-top:20px;"><h3><%= profile.name %></h3></td>
            <td style="border-top:1px solid lightgrey; text-align:center; padding-top:10px;"><%= image_tag profile.thumbnail.to_s, :size =>'150x150' %></td>
            <td style="border-top:1px solid lightgrey; text-align:center; padding-top:20px;"><h5><%= profile.birthday %></h5></td>
            <td style="border-top:1px solid lightgrey; text-align:center; padding-top:20px;"><%= link_to '詳細', profile, class: 'btn btn-light text-dark border-dark' %></td>
            <td style="border-top:1px solid lightgrey; text-align:center; padding-top:20px;"><%= link_to '編集', new_profile_path, class: 'btn btn-light text-dark border-dark' %></td>
            <td style="border-top:1px solid lightgrey; text-align:center; padding-top:20px;"><%= link_to '削除', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light text-dark border-dark' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>  
<br>
<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<hr style="height:4px; background-color:#49b99e; border:none;">
<br>
<%# <p> %>
  <%# <strong>ID:</strong> %>
  <%# <%= @profile.user_id %> 
<%# </p> %>

<div class="container">
  <div class="card border-0" style="background-color:#f5f5f5; text-align:center;">
      <div>
        <%= image_tag @profile.thumbnail.to_s, width: '45%', height: '65%' %>
      </div>
      <br><br>
      <div class="row border-bottom pb-2">
        <div class="col-md-2 col-sm-2 col-xs-3 col-xl-3 col-lg-3"></div>
        <div class="col-md-3 col-sm-4 col-xs-3 col-xl-3 col-lg-3" style="font-size:40px;">名前:</div>
        <div class="col-md-4 col-sm-4 col-xs-3 col-xl-3 col-lg-3" style="font-size:40px;"><%= @profile.name %></div>
        <div class="col-md-3 col-sm-2 col-xs-3 col-xl-3 col-lg-3"></div>
      </div><br>
      <div class="row border-bottom pb-2">
        <div class="col-md-2 col-sm-1 col-lg-3 col-xl-3"></div>
        <div class="col-md-3 col-sm-4 col-lg-3 col-xl-3" style="font-size:40px;">誕生日:</div>
        <div class="col-md-4 col-sm-5 col-lg-3 col-xl-3" style="font-size:40px;"><%= @profile.birthday %></div>
        <div class="col-md-3 col-sm-2 col-lg-3 col-xl-3"></div>
      </div>
      <br>
  </div>     
</div>
<br>
<div style="text-align:center;">
  <%= link_to '戻る', profiles_path, class: 'btn btn-light border-primary text-primary font-weight-bold' %>
</div>
<br><br>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Texts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Post</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.content %></td>
        <td><%= text.user_id %></td>
        <td><%= text.post_id %></td>
        <td><%= text.name %></td>
        <td><%= link_to '詳細', text %></td>
        <td><%= link_to '編集', edit_text_path(text) %></td>
        <td><%= link_to '削除', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @text.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @text.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @text.post_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @text.name %>
</p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>